name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: sms32
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub Pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --depth=1 --branch=output https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} output
          cp dist/github-contribution-grid-snake.svg output/
          cd output
          git add .
          git commit -m "update snake animation"
          git push
